services:
  mysql:
    image: mysql:8.0
    container_name: treinahub_mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: treinahub
      MYSQL_USER: treinaedu
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - treinahub

  mailpit:
    image: axllent/mailpit
    container_name: treinahub_mailpit
    ports:
      - "1027:1025"
      - "8027:8025"
    networks:
      - treinahub

volumes:
  mysql_data:

networks:
  treinahub:
    driver: bridge
